#!/usr/bin/env python3
"""
Stream Ciphers: from keystream fundamentals to authenticated encryption.

This self-contained program demonstrates:
- XOR-based stream-cipher mechanics
- Stateful keystream generation
- A toy LFSR and why predictable generators are insecure
- ChaCha20-style ARX construction
- Nonce/counter handling
- Streaming encryption and decryption
- Bit-flip malleability of unauthenticated stream encryption
- A keyed integrity layer using HMAC-SHA256
- Replay detection using message identifiers
- Known-plaintext and keystream-reuse demonstrations
- Validation, error handling, and performance considerations

The cryptographic implementations in this file are educational. The toy
generators are intentionally not suitable for protecting real data.
For production systems, use a vetted authenticated-encryption primitive
such as ChaCha20-Poly1305 or AES-GCM through a maintained cryptographic
library.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
import struct
import time
from dataclasses import dataclass
from typing import Iterable, Iterator


# ---------------------------------------------------------------------------
# Basic stream-cipher mechanism
# ---------------------------------------------------------------------------

def xor_bytes(left: bytes, right: bytes) -> bytes:
    """XOR two byte strings of equal length."""
    if len(left) != len(right):
        raise ValueError("XOR operands must have equal length")
    return bytes(a ^ b for a, b in zip(left, right))


def xor_with_keystream(data: bytes, keystream: bytes) -> bytes:
    """
    Encrypt or decrypt a data segment.

    Stream ciphers use the same operation in both directions:
        ciphertext = plaintext XOR keystream
        plaintext  = ciphertext XOR keystream
    """
    if len(keystream) < len(data):
        raise ValueError("Keystream is shorter than the input")
    return xor_bytes(data, keystream[:len(data)])


def demonstrate_xor_principle() -> None:
    print("\n=== XOR stream-cipher principle ===")

    plaintext = b"HELLO STREAM"
    keystream = bytes.fromhex("8a1c3f77a02d9e314c8f12aa")
    ciphertext = xor_with_keystream(plaintext, keystream)
    recovered = xor_with_keystream(ciphertext, keystream)

    print("Plaintext :", plaintext)
    print("Keystream :", keystream.hex())
    print("Ciphertext:", ciphertext.hex())
    print("Recovered :", recovered)

    assert recovered == plaintext


# ---------------------------------------------------------------------------
# Toy LFSR stream generator
# ---------------------------------------------------------------------------

class LFSR:
    """
    A deliberately small linear-feedback shift register.

    This is useful for understanding state evolution, feedback taps, and
    keystream generation. It is NOT cryptographically secure because its
    linear structure makes its output susceptible to state reconstruction.
    """

    def __init__(self, seed: int, width: int = 16, taps: tuple[int, ...] = (0, 2, 3, 5)):
        if width <= 1:
            raise ValueError("LFSR width must be greater than one")
        if seed <= 0 or seed >= (1 << width):
            raise ValueError("Seed must be non-zero and fit inside the register")
        if any(t < 0 or t >= width for t in taps):
            raise ValueError("LFSR tap is outside the register width")

        self.width = width
        self.mask = (1 << width) - 1
        self.state = seed
        self.taps = taps

    def next_bit(self) -> int:
        feedback = 0
        for tap in self.taps:
            feedback ^= (self.state >> tap) & 1

        output = self.state & 1
        self.state = ((self.state >> 1) | (feedback << (self.width - 1))) & self.mask
        return output

    def keystream(self, length: int) -> bytes:
        if length < 0:
            raise ValueError("Length cannot be negative")

        output = bytearray()
        for _ in range(length):
            value = 0
            for bit_position in range(8):
                value |= self.next_bit() << bit_position
            output.append(value)
        return bytes(output)


def demonstrate_lfsr() -> None:
    print("\n=== Toy LFSR keystream ===")

    generator = LFSR(seed=0xACE1)
    stream = generator.keystream(16)

    print("Generated bytes:", stream.hex())
    print("Important: linear feedback makes this generator unsuitable for real security.")


# ---------------------------------------------------------------------------
# ChaCha20-style primitive
# ---------------------------------------------------------------------------

def rotate_left_32(value: int, amount: int) -> int:
    value &= 0xFFFFFFFF
    return ((value << amount) | (value >> (32 - amount))) & 0xFFFFFFFF


def quarter_round(state: list[int], a: int, b: int, c: int, d: int) -> None:
    """
    ChaCha quarter round.

    The construction combines addition modulo 2^32, XOR, and rotation.
    This ARX structure avoids lookup tables and provides strong diffusion
    when used in the complete ChaCha construction.
    """
    state[a] = (state[a] + state[b]) & 0xFFFFFFFF
    state[d] ^= state[a]
    state[d] = rotate_left_32(state[d], 16)

    state[c] = (state[c] + state[d]) & 0xFFFFFFFF
    state[b] ^= state[c]
    state[b] = rotate_left_32(state[b], 12)

    state[a] = (state[a] + state[b]) & 0xFFFFFFFF
    state[d] ^= state[a]
    state[d] = rotate_left_32(state[d], 8)

    state[c] = (state[c] + state[d]) & 0xFFFFFFFF
    state[b] ^= state[c]
    state[b] = rotate_left_32(state[b], 7)


def chacha20_block(key: bytes, counter: int, nonce: bytes) -> bytes:
    """
    Produce one 64-byte ChaCha20 keystream block.

    This follows the RFC 8439 ChaCha20 block construction:
    256-bit key, 32-bit block counter, and 96-bit nonce.
    """
    if len(key) != 32:
        raise ValueError("ChaCha20 key must be exactly 32 bytes")
    if len(nonce) != 12:
        raise ValueError("ChaCha20 nonce must be exactly 12 bytes")
    if not 0 <= counter <= 0xFFFFFFFF:
        raise ValueError("Counter must fit in 32 bits")

    constants = b"expand 32-byte k"
    state = list(struct.unpack("<4I", constants))
    state += list(struct.unpack("<8I", key))
    state.append(counter)
    state += list(struct.unpack("<3I", nonce))

    working = state.copy()

    for _ in range(10):
        # Column rounds mix words in each logical column.
        quarter_round(working, 0, 4, 8, 12)
        quarter_round(working, 1, 5, 9, 13)
        quarter_round(working, 2, 6, 10, 14)
        quarter_round(working, 3, 7, 11, 15)

        # Diagonal rounds connect the columns and improve diffusion.
        quarter_round(working, 0, 5, 10, 15)
        quarter_round(working, 1, 6, 11, 12)
        quarter_round(working, 2, 7, 8, 13)
        quarter_round(working, 3, 4, 9, 14)

    result = [
        (original + transformed) & 0xFFFFFFFF
        for original, transformed in zip(state, working)
    ]
    return struct.pack("<16I", *result)


class ChaCha20Educational:
    """
    Minimal RFC 8439-compatible ChaCha20 encryption core.

    The same method encrypts and decrypts because XOR is self-inverting.
    """

    def __init__(self, key: bytes, nonce: bytes, initial_counter: int = 1):
        if len(key) != 32:
            raise ValueError("Key must be 32 bytes")
        if len(nonce) != 12:
            raise ValueError("Nonce must be 12 bytes")
        if not 0 <= initial_counter <= 0xFFFFFFFF:
            raise ValueError("Initial counter must fit in 32 bits")

        self.key = bytes(key)
        self.nonce = bytes(nonce)
        self.initial_counter = initial_counter

    def keystream(self, length: int) -> bytes:
        if length < 0:
            raise ValueError("Length cannot be negative")

        result = bytearray()
        counter = self.initial_counter

        while len(result) < length:
            result.extend(chacha20_block(self.key, counter, self.nonce))
            if counter == 0xFFFFFFFF and len(result) < length:
                raise OverflowError("ChaCha20 counter exhausted")
            counter += 1

        return bytes(result[:length])

    def crypt(self, data: bytes) -> bytes:
        return xor_bytes(data, self.keystream(len(data)))


def demonstrate_chacha20() -> None:
    print("\n=== ChaCha20-style stream encryption ===")

    key = bytes(range(32))
    nonce = bytes.fromhex("000102030405060708090a0b")
    message = (
        b"Stream ciphers turn encryption into a keystream XOR operation. "
        b"Nonce uniqueness is essential."
    )

    cipher = ChaCha20Educational(key, nonce)
    ciphertext = cipher.crypt(message)
    recovered = ChaCha20Educational(key, nonce).crypt(ciphertext)

    print("Ciphertext:", ciphertext.hex())
    print("Recovered :", recovered.decode("utf-8"))
    assert recovered == message


# ---------------------------------------------------------------------------
# Streaming interfaces
# ---------------------------------------------------------------------------

def encrypt_stream(
    chunks: Iterable[bytes],
    key: bytes,
    nonce: bytes,
    initial_counter: int = 1,
) -> Iterator[bytes]:
    """
    Encrypt an iterable of chunks without requiring the whole message
    to reside in memory.

    The counter is advanced according to the number of 64-byte blocks
    consumed, while partial blocks are handled by retaining unused
    keystream bytes.
    """
    if len(key) != 32 or len(nonce) != 12:
        raise ValueError("Invalid ChaCha20 key or nonce")

    counter = initial_counter
    pending_keystream = b""

    for chunk in chunks:
        if not isinstance(chunk, bytes):
            raise TypeError("Stream chunks must be bytes")
        if not chunk:
            continue

        needed = len(chunk)
        stream = bytearray()

        while len(stream) < needed:
            if pending_keystream:
                take = min(needed - len(stream), len(pending_keystream))
                stream.extend(pending_keystream[:take])
                pending_keystream = pending_keystream[take:]
            else:
                if counter > 0xFFFFFFFF:
                    raise OverflowError("ChaCha20 counter exhausted")
                block = chacha20_block(key, counter, nonce)
                counter += 1
                take = min(needed - len(stream), len(block))
                stream.extend(block[:take])
                pending_keystream = block[take:]

        yield xor_bytes(chunk, bytes(stream))


def demonstrate_streaming() -> None:
    print("\n=== Chunked streaming encryption ===")

    key = secrets.token_bytes(32)
    nonce = secrets.token_bytes(12)

    source_chunks = [
        b"First segment of a large",
        b" message transported as",
        b" independent byte chunks.",
    ]

    encrypted_chunks = list(encrypt_stream(source_chunks, key, nonce))
    decrypted_chunks = list(encrypt_stream(encrypted_chunks, key, nonce))

    plaintext = b"".join(decrypted_chunks)
    print("Encrypted chunk count:", len(encrypted_chunks))
    print("Recovered message     :", plaintext.decode())
    assert plaintext == b"".join(source_chunks)


# ---------------------------------------------------------------------------
# Nonce reuse demonstration
# ---------------------------------------------------------------------------

def demonstrate_nonce_reuse_failure() -> None:
    print("\n=== Why nonce reuse is dangerous ===")

    key = secrets.token_bytes(32)
    nonce = secrets.token_bytes(12)

    first = b"Transfer amount: 1000"
    second = b"Transfer amount: 9000"

    cipher = ChaCha20Educational(key, nonce)
    c1 = cipher.crypt(first)
    c2 = ChaCha20Educational(key, nonce).crypt(second)

    # XORing ciphertexts encrypted with the same keystream removes the
    # keystream and exposes the XOR of the plaintexts.
    shared_length = min(len(c1), len(c2))
    relation = xor_bytes(c1[:shared_length], c2[:shared_length])
    plaintext_relation = xor_bytes(first[:shared_length], second[:shared_length])

    print("C1 XOR C2 :", relation.hex())
    print("P1 XOR P2 :", plaintext_relation.hex())
    print("Equal XORs:", relation == plaintext_relation)
    assert relation == plaintext_relation

    print(
        "A unique nonce for every encryption under the same key prevents "
        "this catastrophic keystream reuse."
    )


# ---------------------------------------------------------------------------
# Malleability demonstration
# ---------------------------------------------------------------------------

def demonstrate_malleability() -> None:
    print("\n=== Unauthenticated stream encryption is malleable ===")

    key = secrets.token_bytes(32)
    nonce = secrets.token_bytes(12)

    original = b"role=user;balance=1000"
    cipher = ChaCha20Educational(key, nonce)
    ciphertext = bytearray(cipher.crypt(original))

    old = ord("u")
    new = ord("a")
    position = original.index(b"u")

    # Because C = P XOR K, changing C by P_old XOR P_new changes the
    # decrypted plaintext by exactly the same bit difference.
    ciphertext[position] ^= old ^ new

    modified_plaintext = ChaCha20Educational(key, nonce).crypt(bytes(ciphertext))

    print("Original :", original)
    print("Modified :", modified_plaintext)
    assert modified_plaintext == b"role=aser;balance=1000"

    print(
        "Confidentiality alone does not provide integrity. "
        "Authenticated encryption prevents accepting such modifications."
    )


# ---------------------------------------------------------------------------
# Authenticated stream encryption model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AuthenticatedMessage:
    nonce: bytes
    ciphertext: bytes
    tag: bytes
    message_id: bytes


class HMACStreamCipher:
    """
    Educational encrypt-then-MAC construction.

    The encryption primitive is ChaCha20. HMAC-SHA256 authenticates the
    message identifier, nonce, ciphertext, and associated data.

    A production application should normally use a standardized AEAD
    construction instead of designing its own composition.
    """

    def __init__(self, encryption_key: bytes, authentication_key: bytes):
        if len(encryption_key) != 32:
            raise ValueError("Encryption key must be 32 bytes")
        if len(authentication_key) < 32:
            raise ValueError("Authentication key must contain at least 32 bytes")

        self.encryption_key = bytes(encryption_key)
        self.authentication_key = bytes(authentication_key)

    def _mac_input(
        self,
        message_id: bytes,
        nonce: bytes,
        ciphertext: bytes,
        associated_data: bytes,
    ) -> bytes:
        lengths = struct.pack(
            "<IIII",
            len(message_id),
            len(nonce),
            len(ciphertext),
            len(associated_data),
        )
        return lengths + message_id + nonce + ciphertext + associated_data

    def encrypt(
        self,
        plaintext: bytes,
        *,
        message_id: bytes,
        associated_data: bytes = b"",
    ) -> AuthenticatedMessage:
        if not message_id:
            raise ValueError("message_id must not be empty")

        nonce = secrets.token_bytes(12)
        ciphertext = ChaCha20Educational(
            self.encryption_key, nonce
        ).crypt(plaintext)

        tag = hmac.new(
            self.authentication_key,
            self._mac_input(message_id, nonce, ciphertext, associated_data),
            hashlib.sha256,
        ).digest()

        return AuthenticatedMessage(
            nonce=nonce,
            ciphertext=ciphertext,
            tag=tag,
            message_id=message_id,
        )

    def decrypt(
        self,
        message: AuthenticatedMessage,
        *,
        associated_data: bytes = b"",
    ) -> bytes:
        expected = hmac.new(
            self.authentication_key,
            self._mac_input(
                message.message_id,
                message.nonce,
                message.ciphertext,
                associated_data,
            ),
            hashlib.sha256,
        ).digest()

        if not hmac.compare_digest(expected, message.tag):
            raise ValueError("Authentication failed")

        return ChaCha20Educational(
            self.encryption_key, message.nonce
        ).crypt(message.ciphertext)


class ReplayGuard:
    """Tracks authenticated message identifiers that have already been accepted."""

    def __init__(self, maximum_entries: int = 10000):
        if maximum_entries <= 0:
            raise ValueError("maximum_entries must be positive")
        self.maximum_entries = maximum_entries
        self._seen: set[bytes] = set()

    def accept(self, message_id: bytes) -> None:
        if message_id in self._seen:
            raise ValueError("Replay detected")

        if len(self._seen) >= self.maximum_entries:
            raise OverflowError("Replay window capacity exhausted")

        self._seen.add(message_id)


def demonstrate_authenticated_encryption() -> None:
    print("\n=== Authenticated stream encryption ===")

    encryption_key = secrets.token_bytes(32)
    authentication_key = secrets.token_bytes(32)
    service = HMACStreamCipher(encryption_key, authentication_key)
    replay_guard = ReplayGuard()

    message_id = secrets.token_bytes(16)
    associated_data = b"channel=payments;version=1"
    plaintext = b"payment_id=TX-2048;amount=2500;currency=INR"

    encrypted = service.encrypt(
        plaintext,
        message_id=message_id,
        associated_data=associated_data,
    )

    replay_guard.accept(encrypted.message_id)
    recovered = service.decrypt(
        encrypted,
        associated_data=associated_data,
    )

    print("Nonce      :", encrypted.nonce.hex())
    print("Ciphertext :", encrypted.ciphertext.hex())
    print("Auth tag   :", encrypted.tag.hex())
    print("Recovered  :", recovered.decode())

    assert recovered == plaintext

    # Altering ciphertext changes the MAC input, so verification fails before
    # modified plaintext is released to the caller.
    tampered_ciphertext = bytearray(encrypted.ciphertext)
    tampered_ciphertext[0] ^= 1

    tampered = AuthenticatedMessage(
        nonce=encrypted.nonce,
        ciphertext=bytes(tampered_ciphertext),
        tag=encrypted.tag,
        message_id=encrypted.message_id,
    )

    try:
        service.decrypt(tampered, associated_data=associated_data)
    except ValueError as exc:
        print("Tampering rejected:", exc)
    else:
        raise AssertionError("Tampered ciphertext should not authenticate")

    try:
        replay_guard.accept(encrypted.message_id)
    except ValueError as exc:
        print("Replay rejected:", exc)
    else:
        raise AssertionError("Replay should have been rejected")


# ---------------------------------------------------------------------------
# Known-plaintext keystream recovery
# ---------------------------------------------------------------------------

def demonstrate_known_plaintext_property() -> None:
    print("\n=== Known-plaintext keystream relation ===")

    key = secrets.token_bytes(32)
    nonce = secrets.token_bytes(12)

    known_plaintext = b"HTTP/1.1 200 OK"
    ciphertext = ChaCha20Educational(key, nonce).crypt(known_plaintext)

    recovered_keystream = xor_bytes(known_plaintext, ciphertext)
    reconstructed = xor_bytes(b"SECRET RESPONSE", recovered_keystream)

    actual = ChaCha20Educational(key, nonce).crypt(b"SECRET RESPONSE")

    print("Recovered keystream prefix:", recovered_keystream.hex())
    print("Matches actual prefix     :", reconstructed == actual)
    assert reconstructed == actual

    print(
        "Knowing plaintext can reveal the corresponding keystream bytes. "
        "A secure stream cipher must prevent those bytes from predicting "
        "future or unrelated keystream output."
    )


# ---------------------------------------------------------------------------
# File-oriented streaming encryption
# ---------------------------------------------------------------------------

def transform_file(
    input_path: str,
    output_path: str,
    key: bytes,
    nonce: bytes,
    chunk_size: int = 64 * 1024,
) -> None:
    """
    Encrypt or decrypt a file incrementally.

    The function writes only transformed bytes. Metadata such as nonce,
    authentication tag, and protocol version would need a defined file
    format in a production implementation.
    """
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")

    counter = 1
    pending_keystream = b""

    with open(input_path, "rb") as source, open(output_path, "wb") as target:
        while True:
            chunk = source.read(chunk_size)
            if not chunk:
                break

            stream = bytearray()

            while len(stream) < len(chunk):
                if pending_keystream:
                    take = min(len(chunk) - len(stream), len(pending_keystream))
                    stream.extend(pending_keystream[:take])
                    pending_keystream = pending_keystream[take:]
                else:
                    if counter > 0xFFFFFFFF:
                        raise OverflowError("ChaCha20 counter exhausted")
                    block = chacha20_block(key, counter, nonce)
                    counter += 1
                    take = min(len(chunk) - len(stream), len(block))
                    stream.extend(block[:take])
                    pending_keystream = block[take:]

            target.write(xor_bytes(chunk, bytes(stream)))


# ---------------------------------------------------------------------------
# Validation and edge cases
# ---------------------------------------------------------------------------

def demonstrate_validation() -> None:
    print("\n=== Validation and failure conditions ===")

    invalid_cases = [
        ("short key", lambda: ChaCha20Educational(b"x" * 31, b"y" * 12)),
        ("short nonce", lambda: ChaCha20Educational(b"x" * 32, b"y" * 11)),
        ("invalid LFSR seed", lambda: LFSR(0)),
        ("negative stream length", lambda: ChaCha20Educational(b"x" * 32, b"y" * 12).keystream(-1)),
    ]

    for name, operation in invalid_cases:
        try:
            operation()
        except (ValueError, OverflowError, TypeError) as exc:
            print(f"{name}: rejected with {type(exc).__name__}: {exc}")
        else:
            raise AssertionError(f"{name} was not rejected")


# ---------------------------------------------------------------------------
# Performance measurement
# ---------------------------------------------------------------------------

def benchmark_keystream() -> None:
    print("\n=== Small performance measurement ===")

    key = b"K" * 32
    nonce = b"N" * 12
    payload = b"x" * (1024 * 1024)

    cipher = ChaCha20Educational(key, nonce)
    start = time.perf_counter()
    encrypted = cipher.crypt(payload)
    elapsed = time.perf_counter() - start

    mib_per_second = (len(encrypted) / (1024 * 1024)) / max(elapsed, 1e-12)

    print(f"Processed: {len(encrypted):,} bytes")
    print(f"Elapsed  : {elapsed:.4f} seconds")
    print(f"Rate     : {mib_per_second:.2f} MiB/s")
    print(
        "This pure-Python implementation is useful for studying the algorithm, "
        "not for production throughput."
    )


# ---------------------------------------------------------------------------
# Self-checks
# ---------------------------------------------------------------------------

def run_self_checks() -> None:
    key = bytes(range(32))
    nonce = bytes(range(12))

    vector = chacha20_block(key, 1, nonce)
    assert len(vector) == 64

    plaintext = b"test stream cipher"
    ciphertext = ChaCha20Educational(key, nonce).crypt(plaintext)
    assert ChaCha20Educational(key, nonce).crypt(ciphertext) == plaintext

    chunks = [b"a", b"bc", b"defgh", b"ijklmnop" * 9]
    encrypted = list(encrypt_stream(chunks, key, nonce))
    decrypted = list(encrypt_stream(encrypted, key, nonce))
    assert b"".join(decrypted) == b"".join(chunks)

    service = HMACStreamCipher(key, b"A" * 32)
    msg = service.encrypt(b"authenticated", message_id=b"message-1")
    assert service.decrypt(msg) == b"authenticated"


def main() -> None:
    print("STREAM CIPHERS: TECHNICAL DEMONSTRATION")

    run_self_checks()
    demonstrate_xor_principle()
    demonstrate_lfsr()
    demonstrate_chacha20()
    demonstrate_streaming()
    demonstrate_nonce_reuse_failure()
    demonstrate_malleability()
    demonstrate_authenticated_encryption()
    demonstrate_known_plaintext_property()
    demonstrate_validation()
    benchmark_keystream()

    print("\n=== Production boundary ===")
    print(
        "For real systems, use a maintained cryptographic library and an "
        "authenticated-encryption construction. Never reuse a nonce with "
        "the same key when the selected primitive requires nonce uniqueness."
    )


if __name__ == "__main__":
    main()
